method:
 - GET
 - POST
 - PUT
 - DELETE
 - PATCH
 - TRACE
 - OPTIONS
 - HEAD
 - CONNECT
headers:
 - X-Forwarded-For
 - Host
 - X-Originating-IP
 - X-Forwarded
 - X-Remote-IP
 - X-Remote-Addr
 - X-Original-URL
 - Client-IP
 - True-Client-IP
 - Cluster-Client-IP
 - X-ProxyUser-Ip
 